plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
